In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [55]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512, bias=True),
            nn.ReLU(),
            nn.Linear(512, 512, bias=True),
            nn.ReLU(),
            nn.Linear(512, 10, bias=True),
        )
    
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits
        
    
my_nn = Net()
print(my_nn)

Net(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [56]:
my_nn.linear_relu_stack[2]

Linear(in_features=512, out_features=512, bias=True)

In [50]:
for name, param in my_nn.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")

Layer: linear_relu_stack.0.weight | Size: torch.Size([512, 784]) | Values : tensor([[ 0.0097, -0.0198,  0.0102,  ..., -0.0285,  0.0237,  0.0202],
        [-0.0076, -0.0356,  0.0179,  ..., -0.0016,  0.0250, -0.0133]],
       grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.2.weight | Size: torch.Size([512, 512]) | Values : tensor([[-0.0158,  0.0197,  0.0352,  ..., -0.0313,  0.0398, -0.0101],
        [-0.0334, -0.0011,  0.0299,  ...,  0.0415,  0.0432,  0.0374]],
       grad_fn=<SliceBackward>) 

Layer: linear_relu_stack.4.weight | Size: torch.Size([10, 512]) | Values : tensor([[ 0.0357, -0.0224,  0.0035,  ...,  0.0009, -0.0207, -0.0197],
        [ 0.0402,  0.0433,  0.0160,  ..., -0.0355,  0.0184, -0.0300]],
       grad_fn=<SliceBackward>) 



In [43]:
for layer in list(my_nn.children()):
    print(layer.__class__.__name__)

Flatten
Sequential


In [4]:
x = torch.rand(10)
F.log_softmax(x, dim=0)

tensor([-2.0134, -2.5389, -2.1242, -2.1624, -2.2485, -2.7625, -2.3273, -1.9217,
        -2.7560, -2.5668])

In [16]:
random_data = torch.rand((1, 1, 28, 28)).flatten()
result = my_nn(random_data)

In [10]:
params = list(my_nn.parameters())

In [24]:
params[-1]

Parameter containing:
tensor([-0.0975,  0.0506,  0.0680,  0.0578, -0.0872,  0.0892, -0.0444, -0.0834,
        -0.0241, -0.0487], requires_grad=True)

In [21]:
params[0]

Parameter containing:
tensor([[ 0.0005,  0.0221, -0.0236,  ..., -0.0141, -0.0305,  0.0249],
        [ 0.0344, -0.0233, -0.0211,  ..., -0.0115, -0.0301, -0.0240],
        [ 0.0247, -0.0026, -0.0207,  ..., -0.0102,  0.0269, -0.0309],
        ...,
        [ 0.0273, -0.0333,  0.0321,  ..., -0.0133,  0.0271, -0.0303],
        [-0.0016,  0.0285, -0.0001,  ..., -0.0167,  0.0185, -0.0030],
        [ 0.0296,  0.0265,  0.0341,  ..., -0.0266, -0.0057, -0.0219]],
       requires_grad=True)

In [15]:
params[0]

Parameter containing:
tensor([[ 0.0005,  0.0221, -0.0236,  ..., -0.0141, -0.0305,  0.0249],
        [ 0.0344, -0.0233, -0.0211,  ..., -0.0115, -0.0301, -0.0240],
        [ 0.0247, -0.0026, -0.0207,  ..., -0.0102,  0.0269, -0.0309],
        ...,
        [ 0.0273, -0.0333,  0.0321,  ..., -0.0133,  0.0271, -0.0303],
        [-0.0016,  0.0285, -0.0001,  ..., -0.0167,  0.0185, -0.0030],
        [ 0.0296,  0.0265,  0.0341,  ..., -0.0266, -0.0057, -0.0219]],
       requires_grad=True)